[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The redirects below are handled automatically by the Next.js plugin.
# Keeping them can cause conflicts.
# The plugin will correctly map API routes to functions and handle routing.
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/___netlify-handler"
#   status = 200
# 
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[build.environment]
  NODE_VERSION = "18" 